server:
  port: 8080


spring:
    datasource:
        name: test
        url: jdbc:postgresql://localhost:5432/test
        username: zhuhejun
        password:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jyun.test.ssp.domain

mapper:
  mappers:  com.jyun.test.ssp.dao
  not-empty: false
  identity: PostgreSQL

#pagehelper
pagehelper:
    helperDialect: PostgreSQL
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

